openapi: 3.0.3
info:
  title: Pokedex API
  description: Simple pokemon api
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/

tags:
  - name: pokemon
    description: Pokemon basic information

  - name: pokemon-details
    description: Pokemon details

paths:
  /pokemon/{pokemonName}:
    get:
      tags:
        - pokemon
      summary: Find pokemon by NAME
      description: Returns a single pokemon
      operationId: getPokemonByName
      parameters:
        - name: pokemonName
          in: path
          description: Name of the pokemon to return
          required: true
          schema:
            type: string

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pokemon'

        '404':
          description: Pokemon not found

  /pokemon-details/{pokemonName}:
    get:
      tags:
        - pokemon-details
      summary: Find pokemon details by NAME
      description: Returns a single pokemon details
      operationId: getPokemonDetailByName
      parameters:
        - name: pokemonName
          in: path
          description: Name of the pokemon details to return
          required: true
          schema:
            type: string

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pokemon-details'

        '404':
          description: Pokemon not found

components:
  schemas:
    pokemon:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        weight:
          type: string
        abilities:
          type: array
          items:
            type: object
            properties:
              ability:
                type: object
                properties:
                  name:
                    type: string
        sprites:
          type: object
          properties:
            backDefault:
              type: string
            frontDefault:
              type: string
        types:
          type: array
          items:
            type: object
            properties:
              type:
                type: object
                properties:
                  name:
                    type: string
    pokemon-details:
      type: object
      properties:
        pokemonSpecie:
          type: object
          properties:
            id:
              type: integer
              format: int32
            name:
              type: string
            flavorTextEntries:
              type: array
              items:
                type: object
                properties:
                  flavorText:
                    type: string
                  language:
                    type: object
                    properties:
                      name:
                        type: string
                  version:
                    type: object
                    properties:
                      name:
                        type: string
        moves:
          type: array
          items:
            type: object
            properties:
              move:
                type: object
                properties:
                  name:
                    type: string

